### ISSUE TITLE
Fixed point contracts?

### ISSUE THREAD

**Issue by copumpkin** [ivy-lang/ivy-bitcoin#1]
I'm trying to express a contract that lets you redeem it if you find the fixed point of a hash function. For example, I wanted to try:

```
contract FixedPoint(val: Value) {
  clause reveal(hash: Bytes) {
    verify sha256(hash) == hash
    unlock val
  }
}
```

Unfortunately Ivy's type system seems to be forbidding this, because the type of `sha256` on a `T` is always a `Sha256(T)`, so equality comparisons will fail to typecheck. Is there a coercion operator or some other way for me to express this? I can express it natively in script pretty easily.

**Comment by danrobinson** [comment]
This is definitely a reasonable feature. Will add a `bytes` coercion function (that'll be a no-op at the VM level)
