### ISSUE TITLE
Feature Request: explain the lightning network in an ivy template

### ISSUE THREAD

**Issue by Giszmo** [ivy-lang/ivy-bitcoin#3]
I'm on the edge of diving into LN and have somewhat of an understanding how the payment channels in LN should work but never got around actually looking int up. If there was an ivy template in the playground, I would have studied it now.

Generally, please put real use cases into the template list and maybe add a description to provide context as motivation for people stumbling onto it.

**Comment by danrobinson** [comment]
Have you looked at the examples and explanations in [the docs](http://docs.ivy-lang.org/bitcoin/language/ExampleContracts.html)? That includes an [explanation of a simple payment channel](http://docs.ivy-lang.org/bitcoin/language/ExampleContracts.html#transferwithtimeout).

If you're looking for examples of more elaborate contracts and protocols, that's certainly something we're hoping to add over time.

**Comment by knocte** [comment]
Yeah I guess ideally we would need an example of a "Punishment-based payment channel" which are the ones used by LN at the moment, AFAIU (I found a really good explanation of it here FTR: https://blog.chainside.net/understanding-payment-channels-4ab018be79d4#2435 , I might try to contribute a contract myself using this article as input).

**Comment by knocte** [comment]
@Giszmo I've created a PR: https://github.com/ivy-lang/ivy-bitcoin/pull/14 . Would be great to know if it helps cover your initial request.
